<?php
	include("config.php");
	include("templates/".TEMPLATE_BACKEND."/header.php");
?>
<script type="text/javascript" src="<?php echo PATH; ?>javascript/cms/ContactImageUpload.php"></script>
<script type="text/javascript" src="<?php echo PATH; ?>javascript/cms/Contacts.php"></script>

<?php	
	echo '<h1>Kontakte</h1>';
	echo '<div style="position:relative;">';
	echo '	Kontakt suchen: <input id="contact_search" type="text" value="" onkeyup="contact_search();" />';
	echo '	<div id="contact_search_results" style="position:absolute; margin:0; border:1px solid black; padding:10px; background-color:#ffffff; display:none;"></div>';
	echo '</div>';
	echo '<br style="clear:both;" />';
	
	echo '<div id="contacts_view"></div>';
	echo '<script> contacts_view(); </script>';
	
	
	//CONTACT ADD DIALOG
	echo '<div id="contact_add_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td>Vorname</td>';
	echo '		<td><input type="text" id="contact_add_firstname" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Nachname</td>';
	echo '		<td><input type="text" id="contact_add_lastname" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Position</td>';
	echo '		<td><input type="text" id="contact_add_position" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Sprachen</td>';
	echo '		<td><input type="text" id="contact_add_languages" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Telefon</td>';
	echo '		<td><input type="text" id="contact_add_phone" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Telefax</td>';
	echo '		<td><input type="text" id="contact_add_fax" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Mobiltelefon</td>';
	echo '		<td><input type="text" id="contact_add_mobile" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>E-Mail</td>';
	echo '		<td><input type="text" id="contact_add_mail" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Geschlecht</td>';
	echo '		<td>';
	echo '			<select id="contact_add_gender">';
	echo '				<option value="m">männlich</option>';
	echo '				<option value="f">weiblich</option>';
	echo '			</select>';
	echo '		</td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Aktiv</td>';
	echo '		<td>';
	echo '			<select id="contact_add_active">';
	echo '				<option value="1">Ja</option>';
	echo '				<option value="0">Nein</option>';
	echo '			</select>';
	echo '		</td>';
	echo '	</tr>';
	echo '</table>';
	echo '	<input type="hidden" id="contact_add_id_department" value="" />';
	echo '</div>';
	
	//CONTACT EDIT DIALOG
	echo '<div id="contact_edit_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td>Vorname</td>';
	echo '		<td><input type="text" id="contact_edit_firstname" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Nachname</td>';
	echo '		<td><input type="text" id="contact_edit_lastname" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Position</td>';
	echo '		<td><input type="text" id="contact_edit_position" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Sprachen</td>';
	echo '		<td><input type="text" id="contact_edit_languages" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Telefon</td>';
	echo '		<td><input type="text" id="contact_edit_phone" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Telefax</td>';
	echo '		<td><input type="text" id="contact_edit_fax" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Mobiltelefon</td>';
	echo '		<td><input type="text" id="contact_edit_mobile" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>E-Mail</td>';
	echo '		<td><input type="text" id="contact_edit_mail" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Geschlecht</td>';
	echo '		<td>';
	echo '			<select id="contact_edit_gender">';
	echo '				<option value="m">männlich</option>';
	echo '				<option value="f">weiblich</option>';
	echo '			</select>';
	echo '		</td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Aktiv</td>';
	echo '		<td>';
	echo '			<select id="contact_edit_active">';
	echo '				<option value="1">Ja</option>';
	echo '				<option value="0">Nein</option>';
	echo '			</select>';
	echo '		</td>';
	echo '	</tr>';
	echo '</table>';
	echo '	<input type="hidden" id="contact_edit_id_contact" value="" />';
	echo '</div>';
	
	//CONTACT REMOVE DIALOG
	echo '<div id="contact_remove_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td colspan="">Sind Sie sicher, dass Sie den Kontakt löschen möchten?</td>';
	echo '	</tr>';
	echo '</table>';
	echo '	<input type="hidden" id="contact_remove_id_contact" value="" />';
	echo '</div>';
	
	//DEPARTMENT ADD DIALOG
	echo '<div id="department_add_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td>Standortname</td>';
	echo '		<td><input type="text" id="department_add_department" /></td>';
	echo '	</tr>';
	echo '</table>';
	echo '<input type="hidden" id="department_add_id_location" />';
	echo '</div>';
	
	//DEPARTMENT EDIT DIALOG
	echo '<div id="department_edit_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '	<tr>';
	echo '		<td>Abteilung</td>';
	echo '		<td><input type="text" id="department_edit_department" /></td>';
	echo '	</tr>';
	echo '</table>';
	echo '<input type="hidden" id="department_edit_id_department" value="" />';
	echo '</div>';

	//DEPARTMENT REMOVE DIALOG
	echo '<div id="department_remove_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td colspan="">Sind Sie sicher, dass Sie die Abteilung löschen möchten?</td>';
	echo '	</tr>';
	echo '</table>';
	echo '<input type="hidden" id="department_remove_id_department" value="" />';
	echo '</div>';
	
	//LOCATION ADD DIALOG
	echo '<div id="location_add_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<th colspan="2">Adresse</th>';
	echo '		<th colspan="2">Kontaktdaten</th>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Standort</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_location" /></td>';
	echo '		<td>Telefon</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_phone" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Firma</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_company" /></td>';
	echo '		<td>Telefax</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_fax" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Titel</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_title" /></td>';
	echo '		<td>Webseite</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_website" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Ansprechpartner<br />Vorname<br />Nachname</td>';
	echo '		<td>';
	echo '			<br /><input style="width:200px;" type="text" id="location_add_firstname" />';
	echo '			<br /><input style="width:200px;" type="text" id="location_add_lastname" />';
	echo '		</td>';
	echo '		<td>E-Mail</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_mail" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Straße<br />Hausnummer</td>';
	echo '		<td>';
	echo '			<input style="width:200px;" type="text" id="location_add_street" />';
	echo '			<br /><input style="width:50px;" type="text" id="location_add_streetnr" />';
	echo '		</td>';
	echo '		<th colspan="2">Öffnungszeiten</th>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Postleitzahl</td>';
	echo '		<td><input style="width:50px;" type="text" id="location_add_zipcode" /></td>';
	echo '		<td>Montag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_monday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Stadt</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_city" /></td>';
	echo '		<td>Dienstag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_tuesday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Land</td>';
	echo '		<td>';
	echo '			<select id="location_add_country_code">';
	$results=q("SELECT * FROM shop_countries ORDER BY country;", $dbshop, __FILE__, __LINE__);
	while( $row=mysqli_fetch_array($results) )
	{
		echo '<option value="'.$row["country_code"].'">'.$row["country"].'</option>';
	}
	echo '			</select>';
	echo '		</td>';
	echo '		<td>Mittwoch</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_wednesday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Donnerstag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_thursday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Freitag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_friday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Sonnabend</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_saturday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Sonntag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_add_sunday" /></td>';
	echo '	</tr>';
	echo '</table>';
	echo '</div>';
	
	//LOCATION EDIT DIALOG
	echo '<div id="location_edit_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<th colspan="2">Adresse</th>';
	echo '		<th colspan="2">Kontaktdaten</th>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Standort</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_location" /></td>';
	echo '		<td>Telefon</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_phone" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Firma</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_company" /></td>';
	echo '		<td>Telefax</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_fax" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Titel</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_title" /></td>';
	echo '		<td>Webseite</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_website" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Ansprechpartner<br />Vorname<br />Nachname</td>';
	echo '		<td>';
	echo '			<br /><input style="width:200px;" type="text" id="location_edit_firstname" />';
	echo '			<br /><input style="width:200px;" type="text" id="location_edit_lastname" />';
	echo '		</td>';
	echo '		<td>E-Mail</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_mail" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Straße<br />Hausnummer</td>';
	echo '		<td>';
	echo '			<input style="width:200px;" type="text" id="location_edit_street" />';
	echo '			<input style="width:50px;" type="text" id="location_edit_streetnr" />';
	echo '		</td>';
	echo '		<th colspan="2">Öffnungszeiten</th>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Postleitzahl</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_zipcode" /></td>';
	echo '		<td>Montag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_monday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Stadt</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_city" /></td>';
	echo '		<td>Dienstag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_tuesday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td>Land</td>';
	echo '		<td>';
	echo '			<select id="location_edit_country_code">';
	$results=q("SELECT * FROM shop_countries ORDER BY country;", $dbshop, __FILE__, __LINE__);
	while( $row=mysqli_fetch_array($results) )
	{
		echo '<option value="'.$row["country_code"].'">'.$row["country"].'</option>';
	}
	echo '			</select>';
	echo '		</td>';
	echo '		<td>Mittwoch</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_wednesday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Donnerstag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_thursday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Freitag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_friday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Sonnabend</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_saturday" /></td>';
	echo '	</tr>';
	echo '	<tr>';
	echo '		<td colspan="2"></td>';
	echo '		<td>Sonntag</td>';
	echo '		<td><input style="width:200px;" type="text" id="location_edit_sunday" /></td>';
	echo '	</tr>';
	echo '</table>';
	echo '<input type="hidden" id="location_edit_id_location" value="" />';
	echo '</div>';
	
	//LOCATION REMOVE DIALOG
	echo '<div id="location_remove_dialog" style="display:none;">';
	echo '<table>';
	echo '	<tr>';
	echo '		<td colspan="">Sind Sie sicher, dass Sie den Standort löschen möchten?</td>';
	echo '	</tr>';
	echo '</table>';
	echo '<input type="hidden" id="location_remove_id_location" value="" />';
	echo '</div>';
	
	include("templates/".TEMPLATE_BACKEND."/footer.php");
?>