<?php

echo'<!doctype html>';
echo'<html>';
echo'<head>';
echo'<meta charset="utf-8">';
echo'<title>Wartungsarbeiten</title>';
echo'</head>';
echo'<body>';
echo'<table style="width:600px;" width="600px" align="center">';
echo'<tr>';
echo'<td colspan="2">';
echo'<img  border="0" src="http://www.mapco.de/images/newsletter/newsletter_kopf.png" alt="MAPCO Autotechnik GmbH" title="MAPCO Autotechnik GmbH" />';
echo'<br /><br />';
echo'</td>';
echo'</tr>';
echo'<tr>';
echo'<td  colspan="2" style="font-size:12px; font-family:Arial, Helvetica, sans-serif;" width="600px" valign="top">';
echo'<h3>Wartungsarbeiten</h3>';
echo'<p style="text-align:justify;">';
echo'Wegen Wartungs- und Updatearbeiten ist unsere Seite vorrübergehend nicht erreichbar.';
echo'</p>';
echo'<p style="text-align:justify;">';
echo'In dringenden Fällen sind wir jederzeit telefonisch unter der Rufnummer (033845) 60030, per Fax unter (033845) 41032';
echo'oder per <a href="mailto:bestellung@mapco.de">E-Mail</a> erreichbar.';
echo'</p>';
echo'<p style="text-align:justify;">';
echo'Wir bitten um Ihr Verständnis.';
echo'</p>';
echo'<p style="text-align:justify;">';
echo'Ihr MAPCO-Team';
echo'</p>';
echo'<br /><br />';
echo'</td>';
echo'</tr>';
echo'<tr>';
echo'<td colspan="2" align="center" style="font-size:9px; font-family:Arial, Helvetica, sans-serif; color:#333333";>';
echo'<p>';
echo'Impressum / Rechtliche Verantwortung';
echo'<br />';
echo'MAPCO Autotechnik GmbH, Moosweg 1, DE-14822 Borkheide ';
echo'<br />';
echo'Telefon: +49 33845 6 00 30 / Telefax: +49 33845 4 10 32';
echo'<br />';
echo'E-Mail: info@mapco.eu / URL: www.mapco.eu';
echo'<br />';
echo'Geschäftsführer: Detlev Seeliger / Registergericht: Amtsgericht Potsdam <br />Registernummer: HRB 3965 / Steuernr.: 048/114/01965 / Ust.-ID-Nr.: DE 138456821 (gemäß § 27a UStG)';
echo'</p>';
echo'</td>';
echo'</tr>';
echo'</table>';
echo'</body>';
echo'</html>';
